package com.kuloglu.foursquareandroid.core

object FourSquare {
    const val CLIENT_ID = "RMGPUOON505FAXPPDDV5QEKRWFKFKD1EES0XVLBWA50DSRN1"
    const val CLIENT_SECRET = "NE5LPMC55KXDMGMJDSP45NZNMZMAETQURDGBAMSO100XMM04"
}